package cm.acentice.ideale.constants;

public enum CommandeStatut {

    ACONFIRMER("ACONFIRMER"),VALIDEE("VALIDEE"),STOCK_VALIDEE("STOCKVALIDE"),STOCK_NON_VALIDEE("STOCK_NON_VALIDEE"),STOCK_EN_ATTENTE("STOCKENATTENTE"),
    ENATTENTEDELIVRAISON("EN_ATTENTE_DE_LIVRAISON"),LIVREE("LIVREE"), ENATTENTEDEPAIEMENT("EN_ATTENTE_DE_PAIEMENT"),
    PAIEMENTPARTIEL("PAIEMENT_PARTIEL"), PAIEMENT_COMPLET("PAIEMENT_COMPLET"),LIVRAISON_PARTIEL("LIVRAISON_PARTIEL"), PAIEMENT_DEPASSE("PAIEMENT_DEPASSE");

    private String name;

    private CommandeStatut(String name) {
    }
}
