version: "3.7"

services:
  db:
    image: postgres
    container_name: ideale_db
    env_file:
      - database.env
    volumes:
        - ${HOME}/Volumes/ideale/db:/var/lib/postgresql/data/
    networks:
      - bridge
    expose:
      - '5432'
    ports:
      - '5442:5432'

networks:
  bridge:
    driver: bridge
