spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IDEALE
    username: postgres
    password: admin
    liquibase:
      enabled: fale
      change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false
