spring:
  security:
    user:
      name: admin
      password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: "classpath:/db/changelog/changelog-master.xml"

  datasource:
    platform: postgres
    url: "jdbc:postgresql://postgres:5432/IDEALE"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  servlet:
    encoding:
      charset: 'UTF-8'
      force-response: true
    context-path: '/ideale/api'

springdoc:
  api-docs:
    path: "/api-docs"

logging:
  level:
    org:
      hibernate:
        type: trace
